airports:
  - "ACF"
  - "ADA"
  - "ADB"
  - "ADL"
  - "AGP"
  - "AKL"
  - "AMS"
  - "ANK"
  - "AOE"
  - "ARN"
  - "ASR"
  - "ATH"
  - "AUH"
  - "AVV"
  - "AZI"
  - "BBU"
  - "BCN"
  - "BDA"
  - "BER"
  - "BHX"
  - "BIO"
  - "BLA"
  - "BMA"
  - "BNE"
  - "BOD"
  - "BQH"
  - "BRE"
  - "BRN"
  - "BRS"
  - "BRU"
  - "BTS"
  - "BTZ"
  - "BUD"
  - "BWU"
  - "BZI"
  - "CBR"
  - "CDG"
  - "CGN"
  - "CJJ"
  - "CPH"
  - "CRL"
  - "DIA"
  - "DIY"
  - "DMM"
  - "DNZ"
  - "DOH"
  - "DUB"
  - "DUS"
  - "DXB"
  - "ECN"
  - "EDI"
  - "EMA"
  - "ERZ"
  - "ESB"
  - "ESK"
  - "EUQ"
  - "FCO"
  - "FRA"
  - "FUK"
  - "FZO"
  - "GLA"
  - "GMP"
  - "GOT"
  - "GSE"
  - "HAM"
  - "HEL"
  - "HEM"
  - "HEW"
  - "HIJ"
  - "HKG"
  - "HLZ"
  - "HND"
  - "ICN"
  - "IGL"
  - "ISL"
  - "IST"
  - "ITM"
  - "IUD"
  - "JAD"
  - "JED"
  - "KEF"
  - "KIJ"
  - "KIX"
  - "KKJ"
  - "KMJ"
  - "KWJ"
  - "KYA"
  - "LBA"
  - "LBG"
  - "LCY"
  - "LEJ"
  - "LGW"
  - "LHR"
  - "LIN"
  - "LIS"
  - "LJU"
  - "LPA"
  - "LSQ"
  - "LTN"
  - "LUX"
  - "MAD"
  - "MBW"
  - "MED"
  - "MEL"
  - "MRS"
  - "MUC"
  - "MXP"
  - "NHD"
  - "NHT"
  - "NKM"
  - "NQT"
  - "NRT"
  - "OKD"
  - "OOL"
  - "OPO"
  - "ORY"
  - "OSL"
  - "OTP"
  - "PER"
  - "PIK"
  - "PMO"
  - "PRG"
  - "PSL"
  - "PUS"
  - "RCS"
  - "RIX"
  - "RKE"
  - "RKV"
  - "RTM"
  - "RUH"
  - "SAW"
  - "SDJ"
  - "SHJ"
  - "SIN"
  - "SJI"
  - "SJJ"
  - "SJO"
  - "SKG"
  - "SKP"
  - "SOF"
  - "SOU"
  - "SSX"
  - "STN"
  - "STR"
  - "SVQ"
  - "SYD"
  - "SYQ"
  - "SZF"
  - "TAE"
  - "TGD"
  - "TIA"
  - "TLL"
  - "TOJ"
  - "TXL"
  - "TZX"
  - "UAB"
  - "UKB"
  - "USN"
  - "VIE"
  - "VLC"
  - "VLN"
  - "VNO"
  - "WAW"
  - "WLG"
  - "WMI"
  - "XFW"
  - "XRH"
  - "XXN"
  - "YEG"
  - "YEI"
  - "YHM"
  - "YHU"
  - "YKZ"
  - "YMX"
  - "YOW"
  - "YRO"
  - "YTZ"
  - "YUL"
  - "YVR"
  - "YWG"
  - "YXD"
  - "YXU"
  - "YYC"
  - "YYZ"
  - "ZAG"
  - "ZAZ"
