origins:
  - IATA: "BER"
    City: "Berlin"
    Country: "Germany"
    DepartureStartDate: "2024-03-20"
    DepartureEndDate: "2024-03-22"
    ArrivalStartDate: "2024-03-24"
    ArrivalEndDate: "2024-03-26"
    SkyScannerID: "eyJzIjoiQkVSIiwiZSI6Ijk1NjczMzgzIiwiaCI6IjI3NTQ3MDUzIn0="
  
  - IATA: "GLA"
    City: "Glasgow"
    Country: "Scotland"
    DepartureStartDate: "2024-03-20"
    DepartureEndDate: "2024-03-22"
    ArrivalStartDate: "2024-03-24"
    ArrivalEndDate: "2024-03-26"
    SkyScannerID: "eyJzIjoiR0xBUyIsImUiOiIyNzU0MTg1MiIsImgiOiIyNzU0MTg1MiJ9"

  - IATA: "EDI"
    City: "Edinburgh"
    Country: "Scotland"
    DepartureStartDate: "2024-03-20"
    DepartureEndDate: "2024-03-22"
    ArrivalStartDate: "2024-03-24"
    ArrivalEndDate: "2024-03-26"
    SkyScannerID: "eyJzIjoiRURJIiwiZSI6Ijk1NjczNjY4IiwiaCI6IjI3NTQwODUxIn0="

  - IATA: "MUC"
    City: "Munich"
    Country: "Germany"
    DepartureStartDate: "2024-03-20"
    DepartureEndDate: "2024-03-22"
    ArrivalStartDate: "2024-03-24"
    ArrivalEndDate: "2024-03-26"
    SkyScannerID: "eyJzIjoiTVVDIiwiZSI6Ijk1NjczNDkxIiwiaCI6IjI3NTQ1MDM0In0="

  - IATA: "FRA"
    City: "Frankfurt"
    Country: "Germany"
    DepartureStartDate: "2024-03-20"
    DepartureEndDate: "2024-03-22"
    ArrivalStartDate: "2024-03-24"
    ArrivalEndDate: "2024-03-26"
    SkyScannerID: "eyJzIjoiRlJBIiwiZSI6Ijk1NjczNjUyIiwiaCI6IjI3NTQxNzA2In0"

  - IATA: "SYD"
    City: "Sydney"
    Country: "Australia"
    DepartureStartDate: "2024-03-20"
    DepartureEndDate: "2024-03-22"
    ArrivalStartDate: "2024-03-24"
    ArrivalEndDate: "2024-03-26"
    SkyScannerID: "eyJzIjoiU1lEIiwiZSI6IjEyODY2NzA1OCIsImgiOiIyNzU0NzA5NyJ9"
