deploy:
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/jared_test2'
  steps:
    - name: Setup SSH Key
      run: |
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > deploy_key
        chmod 600 deploy_key

    - name: Deployment Step
      run: |
        export SSH_ARGS="-o BatchMode=yes -o StrictHostKeyChecking=no"
        # Use the temporary SSH key file for authentication
        ssh -t $SSH_ARGS -i deploy_key root@fairfarefinder.com << 'EOF'
          cd /root/FairFareFinder
          git pull
          go build
          SCREEN_SESSION=$(screen -ls | grep FairFareFinder | awk '{print $1}')
          if [ -n "$SCREEN_SESSION" ]; then
            screen -S "$SCREEN_SESSION" -X quit
          fi
          screen -dmS FairFareFinder ./FairFareFinder web
        EOF

    - name: Cleanup SSH Key
      if: always()
      run: rm -f deploy_key
