
name: Build and Test Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Go environment
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Replace with the required version

      # Step 2: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Step 4: Build the mock-main-db-generator tool
      - name: Build Mock DB Generator
        working-directory: utils/tests/mock-main-db-generator
        run: go build -o mock-main-db-generator

      # Step 5: Generate the mock database
      - name: Generate Test Database
        working-directory: utils/tests/mock-main-db-generator
        run: ./mock-main-db-generator

      # Step 6: Start the application
      - name: Start Main Application
        run: |
          go run main.go --web &
          sleep 5 # Adjust the sleep time if necessary

      # Step 7: Run Tests
      - name: Run Tests
        run: go test -v ./...

      # Step 8: Clean up (optional)
      - name: Clean Up
        run: rm -f data/compiled/main.db

