name: Build and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add this to enable manual triggering

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Go environment
      - name: Set up Go 1.23.1 or later
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23.1

      # Step 2: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: go get -v -t ./...

      # Step 4: Build the mock-main-db-generator tool
      - name: Build Mock DB Generator
        working-directory: utils/tests/mock-main-db-generator
        run: go build -o mock-main-db-generator

      # Step 5: Generate the test database
      - name: Generate Test Database
        working-directory: utils/tests/mock-main-db-generator
        run: ./mock-main-db-generator

      # # Step 6: Start the main application with the --web flag
      # - name: Start Main Application
      #   run: |
      #     go run main.go --web &
      #     sleep 5 # Allow the server time to start

      # Step 7: Run the tests
      - name: Run Tests
        run: go test -v ./...
